version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
    groups:
      vite:
        patterns:
          - "*vite*"
      svelte:
        patterns:
          - "*svelte*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
