name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Test Code
        run: |
          npm install
          npm run check
          npm run build
          go build -v ./...
          go test -v ./...
